project:
  type: book
  output-dir: _book

book:
  title: "Polar Coordinates with plotnine"
  chapters:
    - index.qmd
    - ggplot2-examples.qmd
    - coord-radial-examples.qmd
    - socviz-examples.qmd
    - climate-circles.qmd
    - nightingale.qmd
    - guide-axis-theta.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    respect-user-color-scheme: true
    toc: true
    mainfont: "TeX Gyre Pagella"
    sansfont: "Source Sans 3"
    monofont: "JetBrains Mono"

bibliography: references.bib

execute:
  freeze: auto
  keep-ipynb: false

jupyter: coord-polar-test

publish:
  gh-pages:
    branch: gh-pages
