project:
  type: book
  output-dir: _book

book:
  title: "Polar Coordinates with plotnine"
  chapters:
    - index.qmd
    - ggplot2-examples.qmd
    - coord-radial-examples.qmd
    - socviz-examples.qmd
    - nightingale.qmd

format:
  html:
    theme: cosmo

execute:
  warning: false
