[project]
name = "coord-polar-test"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "plotnine",
    "plotnine-polars",
    "socviz-py>=0.0.5",
    "polars",
    "jupyter",
]

[tool.uv.sources]
# plotnine = { git = "https://github.com/iangow/plotnine", branch = "coord-polar" }
plotnine = { path = "/Users/iangow/git/plotnine", editable = true }
